-- Run after schema.sql in a development Supabase SQL editor (as postgres).
-- Throws on the first failed assertion; all fixtures are rolled back.
-- This test exercises database roles directly and never needs a service key.
begin;

insert into auth.users (id, email) values
  ('a1111111-1111-4111-8111-111111111111', 'linkboard-rls-a@example.invalid'),
  ('b2222222-2222-4222-8222-222222222222', 'linkboard-rls-b@example.invalid');

update public.profiles set username = 'rls-user-a', published = true, links = '[
  {"id":"enabled","title":"Visible","url":"https://example.com","platform":"website","enabled":true},
  {"id":"disabled","title":"Hidden","url":"https://example.com/private","platform":"website","enabled":false}
]'::jsonb where id = 'a1111111-1111-4111-8111-111111111111';
update public.profiles set username = 'rls-user-b', published = false, links = '[
  {"id":"enabled","title":"Draft","url":"https://example.com","platform":"website","enabled":true}
]'::jsonb where id = 'b2222222-2222-4222-8222-222222222222';

set local role anon;
do $$
declare profile jsonb;
begin
  profile := public.get_public_profile('rls-user-a');
  if profile ->> 'username' is distinct from 'rls-user-a' or jsonb_array_length(profile -> 'links') is distinct from 1 then
    raise exception 'FAIL: Public lookup must return exactly the enabled link';
  end if;
  if public.get_public_profile('rls-user-b') is not null then
    raise exception 'FAIL: An unpublished profile must be inaccessible';
  end if;
  if public.get_public_profile('does-not-exist') is not null then
    raise exception 'FAIL: An unknown profile must return null';
  end if;
  begin
    perform * from public.profiles;
    raise exception 'FAIL: Anonymous callers can read raw profiles';
  exception when insufficient_privilege then null;
  end;
  begin
    perform * from public.click_events;
    raise exception 'FAIL: Anonymous callers can read analytics';
  exception when insufficient_privilege then null;
  end;
  begin
    insert into public.click_events (profile_id, link_id) values ('a1111111-1111-4111-8111-111111111111', 'enabled');
    raise exception 'FAIL: Anonymous callers can insert events directly';
  exception when insufficient_privilege then null;
  end;
end;
$$;

select public.track_link_click('a1111111-1111-4111-8111-111111111111', 'enabled');
select public.track_link_click('a1111111-1111-4111-8111-111111111111', 'disabled');
select public.track_link_click('a1111111-1111-4111-8111-111111111111', 'missing');
select public.track_link_click('b2222222-2222-4222-8222-222222222222', 'enabled');
reset role;

set local role authenticated;
select set_config('request.jwt.claim.sub', 'a1111111-1111-4111-8111-111111111111', true);
select set_config('request.jwt.claims', '{"sub":"a1111111-1111-4111-8111-111111111111","role":"authenticated"}', true);
do $$
declare touched integer;
begin
  if (select count(*) from public.profiles) <> 1 then raise exception 'FAIL: Owner A can read another raw profile'; end if;
  if (select count(*) from public.click_events) <> 1 then raise exception 'FAIL: Invalid/draft/disabled click was recorded, or valid click missing'; end if;
  if (select count(*) from public.click_events where created_at between transaction_timestamp() and clock_timestamp()) <> 1 then raise exception 'FAIL: Click timestamp was not generated by the server'; end if;
  update public.profiles set name = 'Owner A edited' where id = 'a1111111-1111-4111-8111-111111111111';
  get diagnostics touched = row_count;
  if touched <> 1 then raise exception 'FAIL: Owner cannot edit their profile'; end if;
  update public.profiles set name = 'Cross-tenant change' where id = 'b2222222-2222-4222-8222-222222222222';
  get diagnostics touched = row_count;
  if touched <> 0 then raise exception 'FAIL: Owner A changed owner B profile'; end if;
  begin
    update public.profiles set id = 'b2222222-2222-4222-8222-222222222222' where id = 'a1111111-1111-4111-8111-111111111111';
    raise exception 'FAIL: Owner can change profile ownership';
  exception when insufficient_privilege then null;
  end;
  begin
    update public.profiles set username = 'rls-user-b' where id = 'a1111111-1111-4111-8111-111111111111';
    raise exception 'FAIL: Duplicate username accepted';
  exception when unique_violation then null;
  end;
  begin
    update public.profiles set links = '[{"id":"bad","title":"Bad","url":"javascript:alert(1)","platform":"website","enabled":true}]'::jsonb
    where id = 'a1111111-1111-4111-8111-111111111111';
    raise exception 'FAIL: Executable link URL accepted';
  exception when check_violation then null;
  end;
  begin
    update public.click_events set created_at = '2000-01-01';
    raise exception 'FAIL: Owner can forge click timestamps';
  exception when insufficient_privilege then null;
  end;
end;
$$;
reset role;

set local role authenticated;
select set_config('request.jwt.claim.sub', 'b2222222-2222-4222-8222-222222222222', true);
select set_config('request.jwt.claims', '{"sub":"b2222222-2222-4222-8222-222222222222","role":"authenticated"}', true);
do $$
begin
  if (select count(*) from public.click_events) <> 0 then raise exception 'FAIL: Owner B can read owner A analytics'; end if;
  if (select count(*) from public.profiles where username = 'rls-user-b') <> 1 then raise exception 'FAIL: Owner B cannot read their unpublished profile'; end if;
  if (select count(*) from public.profiles where username = 'rls-user-a') <> 0 then raise exception 'FAIL: Owner B can read owner A disabled links'; end if;
  if public.get_public_profile('rls-user-a') is null then raise exception 'FAIL: Authenticated visitors cannot view published profiles'; end if;
end;
$$;
reset role;

rollback;
select 'PASS: All Linkboard database authorization tests passed; fixtures rolled back.' as result;
